version: "2.3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_TCP_PORT=3333
    ports:
      - "3333:3333"
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_ROOT_USER -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      timeout: 3s
      retries: 3


