spring:
  datasource:
    url: jdbc:mysql://localhost:3333/camunda?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

camunda.bpm.admin-user:
  id: admin
  password: admin
